name: Deployment Exercise 1
on: push
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:   
      - name: job1 step 1
        run: echo "This is job 1 step 1"

      - name: Job1 step 2
        run: echo "This is job 1 step 2"

      - name: Job1 step 3     
        run: echo "Deploying application for Job1 ..."
  job2: 
    runs-on: ubuntu-latest
    steps:   
      - name: job2 step 1
        run: echo "This is job 2 step 1"

      - name: Job2 step 2
        run: echo "This is job 2 step 2"

      - name: Job2 step 3     
        run: echo "Deploying application for Job2 ..."